# Generated by Django 5.0.4 on 2024-05-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_product_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['key'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['key'], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
    ]
