# Generated by Django 5.0.4 on 2024-04-26 10:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=1000)),
                ('last_name', models.CharField(blank=True, max_length=1000)),
                ('username', models.CharField(blank=True, max_length=1000)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, default='')),
                ('image', models.URLField(blank=True, default='', max_length=10000)),
                ('banner', models.URLField(blank=True, default='', max_length=10000)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5)),
                ('posts', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('followings', models.IntegerField(default=0)),
                ('isVerified', models.BooleanField(default=False)),
                ('isLocked', models.BooleanField(default=False)),
                ('Connections', models.ManyToManyField(blank=True, related_name='Connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
