# Generated by Django 4.2.6 on 2023-12-31 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('isVerified', models.BooleanField(default=False)),
                ('isLocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Profile Configuration',
                'verbose_name_plural': 'Profile Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isLocked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isVerified',
        ),
    ]
