# Generated by Django 5.0.4 on 2024-05-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isMarchant',
            field=models.BooleanField(default=False),
        ),
    ]
