# Generated by Django 4.2.6 on 2024-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProfileConfig',
        ),
    ]
