# Generated by Django 4.2.6 on 2023-10-29 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Connections',
            field=models.ManyToManyField(blank=True, related_name='Connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
