# Generated by Django 4.2.6 on 2023-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_profile_connections_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='bannerImage/defaultBanner.png', upload_to='bannerImage/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='userImage/defaultUser.png', upload_to='userImage/'),
        ),
    ]
