# Generated by Django 4.2.6 on 2023-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_profile_banner_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
