# Generated by Django 4.2.6 on 2024-01-14 07:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), size=None),
        ),
    ]
