# Generated by Django 4.2.6 on 2023-12-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postconfig',
            name='isProtected',
            field=models.BooleanField(default=False),
        ),
    ]
