# Generated by Django 4.2.6 on 2023-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_postconfig_isprotected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postconfig',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
