# Generated by Django 4.2.6 on 2024-01-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postconfig',
            old_name='like',
            new_name='likeNo',
        ),
        migrations.RenameField(
            model_name='postconfig',
            old_name='views',
            new_name='viewsNo',
        ),
        migrations.RemoveField(
            model_name='postconfig',
            name='dislike',
        ),
    ]
