# Generated by Django 4.2.6 on 2023-12-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_postconfig_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
