# Generated by Django 4.2.6 on 2024-01-21 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_comment_remove_postconfig_master_commentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angry', models.ManyToManyField(related_name='angry_post', to=settings.AUTH_USER_MODEL)),
                ('care', models.ManyToManyField(related_name='care_post', to=settings.AUTH_USER_MODEL)),
                ('cry', models.ManyToManyField(related_name='cry_post', to=settings.AUTH_USER_MODEL)),
                ('heart', models.ManyToManyField(related_name='heart_post', to=settings.AUTH_USER_MODEL)),
                ('laugh', models.ManyToManyField(related_name='laugh_post', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.post')),
                ('wow', models.ManyToManyField(related_name='wow_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Reaction',
                'verbose_name_plural': 'Post Reactions',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angry', models.ManyToManyField(related_name='angry_comment', to=settings.AUTH_USER_MODEL)),
                ('care', models.ManyToManyField(related_name='care_comment', to=settings.AUTH_USER_MODEL)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feed.comment')),
                ('cry', models.ManyToManyField(related_name='cry_comment', to=settings.AUTH_USER_MODEL)),
                ('heart', models.ManyToManyField(related_name='heart_comment', to=settings.AUTH_USER_MODEL)),
                ('laugh', models.ManyToManyField(related_name='laugh_comment', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL)),
                ('wow', models.ManyToManyField(related_name='wow_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Reaction',
                'verbose_name_plural': 'Comment Reactions',
            },
        ),
    ]
