# Generated by Django 4.2.6 on 2024-03-24 12:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_postreaction_angry_remove_postreaction_care_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=3),
        ),
    ]
