# Generated by Django 4.2.6 on 2024-04-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0012_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowComments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='commentNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='createdAt',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='hiddenFrom',
            field=models.ManyToManyField(blank=True, related_name='hidden_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isPersonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isProtected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='likeNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='viewsNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='visible_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostConfig',
        ),
    ]
