# Generated by Django 4.2.6 on 2024-04-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_post_allowcomments_post_commentno_post_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
    ]
